version: 2
updates:
  - package-ecosystem: github-actions
    enabled: false
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: npm
    enabled: false
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: pip
    enabled: false
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: uv
    enabled: false
    directory: /
    schedule:
      interval: monthly
